version: 1.0.{build}
skip_tags: true
clone_depth: 1
init:
  - git config --global core.autocrlf input
os: MinGW
install:
  - choco install activeperl
  - choco install make
  - perl -V
  - echo %PATH%
  #- SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%  
build_script:
  - perl Makefile.PL
  - make
test_script:
  - make test
