version: 1.0.{build}
skip_tags: true
clone_depth: 1
init:
  - git config --global core.autocrlf input
# Mingw and Cygwin now builtin: http://www.appveyor.com/updates/2015/05/30
#os: MinGW
install:
  - choco install activeperl
  #- choco install make
  - perl -V
  #- echo %PATH%
  #- curl -o C:\MinGW\bin\gperf.exe -L http://kent.dl.sourceforge.net/project/gnuwin32/gperf/3.0.1/gperf-3.0.1.exe
  - SET PATH=%PATH%;C:\MinGW\bin
  - curl -o dmake.zip -L https://cpan.metacpan.org/authors/id/S/SH/SHAY/dmake-4.12.2.2.zip
  - unzip dmake.zip

build_script:
  - perl Makefile.PL make=dmake
  - dmake\dmake
  #- C:\MinGW\bin\mingw32-make DFSEP=/ NOOP=true INST_ARCHLIB=blib/arch

test_script:
  - dmake\dmake test
  #- C:\MinGW\bin\mingw32-make test DFSEP=/ NOOP=true
